---
title: '빅데이터 분석 시각화 포트폴리오 #2'
author: "이현주"
date: '2019년 3월 18일 (월)'
output: html_document
---

<br>


```{r setup, include=FALSE}
library(ggplot2)
library(ggiraphExtra)
library(ggiraph)
library(kormaps2014)
library(dplyr)
library(tibble)  
theme_set(theme_gray(base_family="AppleGothic"))
par(family = "AppleGothic")
```

----

### 1. 다음과 같이 미국의 범죄율을 한번에 작도하시오.

<br>

```{r echo=TRUE}

# 지도에 그릴 데이터
head(USArrests)

chodata = rownames_to_column(USArrests, var = 'state')
chodata$state = tolower(chodata$state)
head(chodata)

# 지도 데이터
usmap = map_data('state')
head(usmap)


# 작도
ggChoropleth(data=chodata, 
             aes(map_id=state),
             map = usmap,
             title = '',
             reverse = F,
             interactive = T)

```

----

### 2. 미국 범죄율의 Rape부분을 단계 구분도로 작성하시오. (단, 툴팁은 그림과 같이 표현하고,  클릭시 해당 state의 wikipedia 페이지를 보이도록 HTML로 저장하시오) "http://en.wikipedia.org/wiki/<해당 state>"

<br>

```{r echo=TRUE}
# tooltip 마우스 올렸을 때 나타낼 정보
tooltips = paste0(
  sprintf("<p><strong>%s</strong></p>", as.character(chodata$state)),
  '<table>',
  '  <tr>',
  sprintf('<td>%.0f / %.0f 만</td> ', chodata$Rape, chodata$UrbanPop * 10),
  '  </tr>' )

# onclick 할 때 실행할 코드
onclick = sprintf('window.open("http://en.wikipedia.org/wiki/%s")', as.character(chodata$state))

# 작도
ggplot(chodata, aes(map_id = state)) + 
  geom_map_interactive(aes(fill = Rape,
                           tooltip = tooltips,
                           onclick = onclick),
                       map = usmap) + 
  expand_limits(x = usmap$long, y = usmap$lat) +
  labs(title="USA Rape", fill = 'Rape') + 
  scale_fill_gradient2('Rape', low='red', mid = 'green', high = 'blue') -> usa_rape


ggiraph(code = print(usa_rape))
girafe(ggobj = usa_rape)


```


----
### 3. 우리나라 시도별 결핵환자수(kormaps::tbc)를 단계 구분도로 작성하시오. (단, 환자수는 2006년부터 2015년 통합, NA인 지역은 0으로 표시할 것)

<br>
```{r echo=TRUE}
tbc = kormaps2014::tbc

# 결측 처리 NA = 0
table(is.na(tbc))
tbc[is.na(tbc)] = 0   
str(tbc)


# year 컬럼 형변환
tbc$year =  as.character(tbc$year)

tbc2 = tbc %>% filter( year >= '2006' & year <= '2015' ) %>% group_by(name, code) %>% summarise(sum_newpts = sum(NewPts))
head(tbc2)

# tooltip 마우스 올렸을 때 나타낼 정보
tooltips2 = paste0(
  sprintf("<p><strong>%s</strong></p>", as.character(chodata$name)),
  '<table>',
  '    <th>결핵환자수</th>',
  '  <tr>',
  sprintf('<td> %.0f 만</td>', tbc2$sum_newpts),
  '  </tr>')

# 작도
tbc_map = ggplot(tbc2, aes(data = sum_newpts, map_id = code)) +
  geom_map_interactive( aes(fill = sum_newpts,
                            tooltip = tooltips2), map = kormap1) + 
  expand_limits(x = kormap1$long, y = kormap1$lat) +
  scale_fill_gradient2('인구', low='green', mid = 'lightyellow', high = 'red') +
  xlab('경도') + ylab('위도') + 
  labs(title="시도별 결핵환자수")

ggiraph(code = print(tbc_map))
girafe(ggobj = tbc_map)

```
