theme_set(theme_gray(base_family="AppleGothic"))
par(family = "AppleGothic")
library(kormaps2014)
library(ggiraph)
library(ggplot2)
library(ggiraphExtra)
library(dplyr)
library(kormaps2014)
data = load('data/score.csv')
kdata = load('data/kdata.rda')