library(kormaps2014)
library(ggiraph)
library(ggplot2)
library(ggiraphExtra)
library(dplyr)
library(tibble)
library(kormaps2014)
library(plotly)
library(dygraphs)
library(xts)
library(gridExtra)
theme_set(theme_gray(base_family="AppleGothic"))
par(family = "AppleGothic")
data = load('data/score.csv')
kdata = load('data/kdata.rda')
